[project]
name = "agentic-ai-google-x-kaggle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "chainlit>=2.9.2",
    "fastapi>=0.118.3",
    "google-adk-community>=0.2.0",
    "google-adk[openmemory]>=1.19.0",
    "langchain[classic]>=1.1.2",
    "langchain-community[requests]>=0.4.1",
    "langchain-gemini>=0.1.1",
    "langchain-google>=0.1.1",
    "langchain-google-genai>=3.2.0",
    "langfuse>=3.10.1",
    "langgraph>=1.0.4",
    "langserve>=0.3.3",
    "markdown>=3.10",
    "opentelemetry-api>=1.37.0",
    "opentelemetry-sdk>=1.37.0",
    "pandas>=2.3.3",
    "pip>=25.3",
    "pymongo>=4.15.4",
    "uvicorn>=0.38.0",
    "weasyprint>=66.0",
    "langchain-classic>=1.0.0",
    "streamlit>=1.52.1",
    "google-api-python-client>=2.187.0",
    "nest-asyncio>=1.6.0",
    "fpdf2>=2.8.5",
    "google-generativeai>=0.8.6",
    "google-genai>=1.55.0",
]
